//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateLabResultReport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:54898/")]
        public string DOCUMENTGENERATOR_BASE_URI {
            get {
                return ((string)(this["DOCUMENTGENERATOR_BASE_URI"]));
            }
            set {
                this["DOCUMENTGENERATOR_BASE_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSSQLSERVER_CONNECTION_STRING")]
        public string CONNECTION_STRING {
            get {
                return ((string)(this["CONNECTION_STRING"]));
            }
            set {
                this["CONNECTION_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEMPLATE_FILE_PATH")]
        public string TEMPLATE_PATH {
            get {
                return ((string)(this["TEMPLATE_PATH"]));
            }
            set {
                this["TEMPLATE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REGULAR_FONT_FILE_PATH")]
        public string REGULAR_FONT_FILE_PATH {
            get {
                return ((string)(this["REGULAR_FONT_FILE_PATH"]));
            }
            set {
                this["REGULAR_FONT_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ITALICS_FONT_FILE_PATH")]
        public string ITALICS_FONT_FILE_PATH {
            get {
                return ((string)(this["ITALICS_FONT_FILE_PATH"]));
            }
            set {
                this["ITALICS_FONT_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOLD_REGULAR_FONT_FILE_PATH")]
        public string BOLD_REGULAR_FONT_FILE_PATH {
            get {
                return ((string)(this["BOLD_REGULAR_FONT_FILE_PATH"]));
            }
            set {
                this["BOLD_REGULAR_FONT_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOLD_ITALICS_FONT_FILE_PATH")]
        public string BOLD_ITALICS_FONT_FILE_PATH {
            get {
                return ((string)(this["BOLD_ITALICS_FONT_FILE_PATH"]));
            }
            set {
                this["BOLD_ITALICS_FONT_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL_QUERY_TO_GRAB_VERSION_NO_AND_AMENDED_STATUS")]
        public string DOCUMENT_VERSION_NO_AND_AMEND_QUERY {
            get {
                return ((string)(this["DOCUMENT_VERSION_NO_AND_AMEND_QUERY"]));
            }
            set {
                this["DOCUMENT_VERSION_NO_AND_AMEND_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REQUISITION_INFO")]
        public string REQUISITION_INFO_QUERY {
            get {
                return ((string)(this["REQUISITION_INFO_QUERY"]));
            }
            set {
                this["REQUISITION_INFO_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RESULTS_BASE")]
        public string RESULTS_BASE_QUERY {
            get {
                return ((string)(this["RESULTS_BASE_QUERY"]));
            }
            set {
                this["RESULTS_BASE_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PANEL_TESTS")]
        public string PANEL_TESTS_QUERY {
            get {
                return ((string)(this["PANEL_TESTS_QUERY"]));
            }
            set {
                this["PANEL_TESTS_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FORMATTED_RESULTS")]
        public string FORMATTED_RESULTS_QUERY {
            get {
                return ((string)(this["FORMATTED_RESULTS_QUERY"]));
            }
            set {
                this["FORMATTED_RESULTS_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MANUAL_RESULTS")]
        public string MANUAL_RESULTS_QUERY {
            get {
                return ((string)(this["MANUAL_RESULTS_QUERY"]));
            }
            set {
                this["MANUAL_RESULTS_QUERY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PANEL_NAME_AND_PANEL_ID")]
        public string PANEL_NAME_AND_PANEL_ID_QUERY {
            get {
                return ((string)(this["PANEL_NAME_AND_PANEL_ID_QUERY"]));
            }
            set {
                this["PANEL_NAME_AND_PANEL_ID_QUERY"] = value;
            }
        }
    }
}
